### ISSUE TITLE
error al convertir xml a pdf

### ISSUE THREAD

**Issue by matiasAS** [tonicanada/sii_chile_xml_to_pdf#1]
Hola, tengo un error al convertir xml a pdf.
El mensaje de error es que el xml no tiene el atributo "timbre", que hago?

Los XML fueron obtenidos de Nubox.

saludos

**Comment by tonicanada** [comment]
Hola Matías, ¿puedes enviarme un xml para que lo pueda probar? Mi email es toni.cm@gmail.com.

**Comment by matiasAS** [comment]
Hola @tonicanada , enviados 6 XML a tu correo. Me cuentas

Saludos

**Comment by tonicanada** [comment]
Matías, lo que ocurre es que los XML que estás usando no tienen el namespace xmlns = "http://www.sii.cl/SiiDte" al principio (normalmente llevan ese tag). Para que funcione debes modificar el archivo "DTE.py", y eliminar el namespace en las funciones donde se usa. 

Ejemplo:
`self.rut_proveedor = self.tree.find('.//{http://www.sii.cl/SiiDte}RUTEmisor').text`
Transformar a:
`self.rut_proveedor = self.tree.find('.//RUTEmisor').text`
